### ISSUE TITLE
Error occurred while enabling MGSnake v1.3.3 (Is it up to date?)

### ISSUE THREAD

**Issue by XxCoolGamesxX** [MC-Minigames/Snake#1]
We have error with plugin.

This server is running Spigot version git-Spigot-952179b-bc03b6f (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Here the error:

```
[20:40:20] [Server thread/INFO]: [MGSnake] Enabling MGSnake v1.3.3
[20:40:20] [Server thread/INFO]: [0;34;1mMGSnake is running on v1_8_R1.[m
[20:40:20] [Server thread/ERROR]: Error occurred while enabling MGSnake v1.3.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R1/World
    at com.comze_instancelabs.mgsnake.Main.onEnable(Main.java:95) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R1.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
    ... 12 more
```

I was look in the code. I see the plugin do not support the 1.8 of spigot. Are you plan to update for the 1.8?

**Comment by mepeisen** [comment]
Hi.
 There is a new project lead.
 You find the new game with support up to 1.10 at https://github.com/MysticCity/Snake
 Please report issues at https://github.com/MysticCity/MinigamesAPI/issues

The current snapshot build is found at http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/Minigames-All-1.14.9-20160619.044520-15-bin.zip
 Please help us with testing. Thanks
